services:
  job-connector-postgres:
    container_name: job-connector-postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bbZvjXpBC1CP0PP
      POSTGRES_DB: job_connector_db
    volumes:
      - job-connector-postgres-data:/var/lib/postgresql/data
    networks:
      - job-connector-network

  job-connector-redis:
    container_name: job-connector-redis
    restart: always
    image: redis:alpine
    volumes:
      - job-connector-redis-data:/data
    networks:
      - job-connector-network

  job-connector-api:
    container_name: job-connector-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      HOST_NAME: job-connector-postgres
      DATABASE_NAME: job_connector_db
      DB_USERNAME: postgres
      DB_PASSWORD: bbZvjXpBC1CP0PP
      JWT_SECRET: vlJF587ye4KcoDifRiI6A148FSQzfpFw
      JWT_EXPIRATION_IN_MINUTES: 5
      JWT_ISSUER: Enigma
      REFRESH_TOKEN_EXPIRATION_IN_HOUR: 24
      REDIS_HOST: job-connector-redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - job-connector-postgres
      - job-connector-redis
    networks:
      - job-connector-network


volumes:
  job-connector-postgres-data:
    name: job-connector-postgres-data
  job-connector-redis-data:
    name: job-connector-redis--data

networks:
  job-connector-network:
    name: job-connector-network
    driver: bridge
